### ISSUE TITLE
Fail when property value is longer then 255 characters

### ISSUE THREAD

**Issue by Tapchicoma** [ec4j/ec4j#118]
Related to https://github.com/pinterest/ktlint/issues/739.

Currently such properties are silently ignored. I would like that ec4j throws an error on such property either every time or when such option is enabled.

**Comment by ppalaga** [comment]
That behavior used to be required by the editorconfig specs and tests. The fix is ready https://github.com/ec4j/ec4j/pull/111 but is blocked by  https://github.com/editorconfig/editorconfig-core-test/pull/41
