### ISSUE TITLE
`NioPath#toString()` does not contain drive letter on Windows

### ISSUE THREAD

**Issue by Vampire** [ec4j/ec4j#126]
If you call `toString()` on a `NioPath` on Windows, the result misses the drive in the beginning.

**Comment by ppalaga** [comment]
Taken very strictly, this would be a backwards incompatible change, so we'd have to bump the major. I'd have no problem with that.

**Comment by Vampire** [comment]
That depends on whether you consider the returned content of `toString()` part of your API. But yeah, very strictly speaking it could be considered breaking.
