### ISSUE TITLE
Please provide some way to get all relevant `.editorconfig` files

### ISSUE THREAD

**Issue by Vampire** [ec4j/ec4j#127]
It would be nice to have a way to get all relevant `.editorconfig` files for a resource.
Currently you can only get the accumulated properties for a resource.
With the ability to get the relevant paths, you can for example set up some monitoring on those files for changes, or specify them as inputs for a Gradle task and so on.
When combining with the cache that is then also used later on when actually needing the properties, this also should not incur significant runtime overhead.
I was not able to somehow manage to get it with `0.3.0` without using reflection to access the `path` field of `NioPath`.
Even using `toString()` on the `Ec4jPath` that is a `NioPath` does not work due to #126.

**Comment by ppalaga** [comment]
> all relevant `.editorconfig` files for a resource

Could you please define "relevant"?

**Comment by Vampire** [comment]
Well, currently you can only say "give me the properties for path X".
I'd like to be able to say "give me the config files considered for path X".
Maybe even with a boolean to get all considered files, or all considered and existing files, as some use-cases like watching the path would also be interested in files not currently existing, some other use-cases like input for a Gradle task would only need the actually existing files.

**Comment by ppalaga** [comment]
> all considered and existing files

I wonder whether that's not something doable through a custom Cache implementation? If a path is looked up in the Cache, then it is "considered" for a path being querried, no? 

If non-existent files should fall into the set, then, I wonder, how it is different from just climbing the parent hierarchy up to the root folder that is either under your control (because you are passing it to ResourcePropertiesService ) or if you do not bother to set any root, then you go up to the filesystem root?

**Comment by Vampire** [comment]
> I wonder whether that's not something doable through a custom Cache implementation? If a path is looked up in the Cache, then it is "considered" for a path being querried, no?

I tried doing it with a custom editor config loader like
```kotlin
val fileCollectingConfigLoader = object : EditorConfigLoader(null, null) {
    private val delegate = of(null)
    val configFiles = mutableListOf<String>()

    override fun load(configFile: Resource?): EditorConfig {
        configFiles.add("${configFile?.path}")
        return delegate.load(configFile)
    }
}

ResourcePropertiesService
    .builder()
    .loader(fileCollectingConfigLoader)
    .build()
    .queryProperties(Resources.ofPath(it.asFile.absoluteFile.toPath(), UTF_8))

val relevantFiles = fileCollectingConfigLoader.configFiles
```
Which did not work due to #128 and the `Ec4jPath` all being package-private and with private fields, so to get the actual `Path` you need to use reflection.

With #128 fixed, it could of course be done like that, but I still consider this more a work-around then and also don't really like relying on `toString` output for production logic.

> If non-existent files should fall into the set, then, I wonder, how it is different from just climbing the parent hierarchy up to the root folder that is either under your control (because you are passing it to ResourcePropertiesService ) or if you do not bother to set any root, then you go up to the filesystem root?

That's exactly what I do right now, just for my case with existence check:
```kotlin
generateSequence(destinationDirectory.asFile) { it.parentFile }
    .map { it.resolve(".editorconfig") }
    .filter { it.isFile }
    .toList()
```

But the difference is, that you also consider `root = true` in a file and this logic does not.
Of course I can also code that logic again customly.
But I'd prefer to not duplicate the logic you already have in ec4j, but just being able to ask ec4j "give me the relevant files", hence this feature request. :-)

**Comment by ppalaga** [comment]
> you also consider `root = true` in a file and this logic does not.

That's true, but as far as I can understand your use case is some sort of IDE where also `root = true` can come and go due to user edits. I wonder whether watching the whole parent hierarchy defined in terms of IDE project of Git repository would not be more robust?

**Comment by ppalaga** [comment]
Having said all the above, I am still open to discuss how the API should change to support your use case.

**Comment by Vampire** [comment]
> That's true, but as far as I can understand your use case is some sort of IDE where also root = true can come and go due to user edits. 

No, actually my use-case is declaring inputs for a Gradle task that does ktlint formatting and thus should not be up-to-date if any of the relevant editorconfig files was changed. So for my concrete use-case only the actually existing files are enough.

The "sort of IDE" use-case is an additional use-case that could be covered by this functionality, just that there the IDE should also monitor not currently existing files and thus needs all of them.
You are of course right, that there the `root = true` could change any time, so either on change that IDE would need to also get the list freshly on change, or indeed just consider all files up to the filesystem root.

As the "soft of IDE" use-case is not my current use-case and just was an additional thought why it might make sense to also report non-existing files, I personally am currently also perfectly fine if I would only get the existing files. :-)
