### ISSUE TITLE
Please release 1.1.0 to Maven Central

### ISSUE THREAD

**Issue by Vampire** [ec4j/ec4j#131]
Version 1.1.0 is missing on Maven Central, but is essential to fix the "empty value" parse error in upstream projects like ktlint.
Please push out the release. :-)

**Comment by ppalaga** [comment]
Strange. Let me scheck, once I am on a reliable conection.

**Comment by Vampire** [comment]
Btw. is it intended, that the URL in the Maven Central POM is pointing to a fork instead of this repo?

**Comment by paul-dingemans** [comment]
@ppalaga Hi Peter,
I hope you have time to look at this issue soonish. I am working towards a new release of ktlint in which I would like to include the update of the dependency so that problem of @Vampire is solved.

**Comment by ppalaga** [comment]
Sorry, I was away. I deployed 1.1.0 once again and it should appear on Central within an hour or so.

**Comment by paul-dingemans** [comment]
Cool and thanks. Just received the renovate update in ktlint.
