### ISSUE TITLE
Deploy ec4j in maven repository

### ISSUE THREAD

**Issue by angelozerr** [ec4j/ec4j#22]
https://github.com/angelozerr/ec4e/ crashes because it consumes ec4j whis is not published in maven repository.

@pascalleclercq It should be cool to publish ec4j and fixes ec4e (like you have done with other project with cloudbees). But before doing that please see with @ppalaga to choose a well group id and see teh work with travis that @ppalaga has done.

I don't know very good cloudbees, maven ,travis, etc @ppalaga and @pascalleclercq please discuss together.

Many thanks guys!

**Comment by ppalaga** [comment]
> https://github.com/angelozerr/ec4e/ crashes because it consumes ec4j whis is not published in maven repository.

I can see it failing for a slightly different reason - see https://github.com/angelozerr/ec4e/issues/18

**Comment by angelozerr** [comment]
Many thanks @pascalleclercq to have fixed ec4e with ec4j.

@ppalaga please see https://github.com/angelozerr/ec4e/blob/master/pom.xml#L117 and give us our comment. Thanks!

**Comment by angelozerr** [comment]
Now the issue is about group id. @pascalleclercq can we use `fr.opensagres` instead of using `org.eclipse` ?

**Comment by ppalaga** [comment]
`ec4j-core` is now available on Maven Central http://central.maven.org/maven2/org/ec4j/core/ec4j-core/
