### ISSUE TITLE
Validate API

### ISSUE THREAD

**Issue by angelozerr** [ec4j/ec4j#23]
@ppalaga I have created this issue to validate any API and classes names of ec4j. Any feedback are welcome (name of class that you d'ont like, API, etc) Thanks!

**Comment by ppalaga** [comment]
Yes, I think I'll have a couple of small proposals. But to be able to discuss and decide about them independently of each other, I think I'll be creating separate issues and link them here.

**Comment by angelozerr** [comment]
>  I think I'll be creating separate issues and link them here.

Sure, I have just created this issue to speak about "validate API", but create an issue per refactoring, change signature will be better. Thanks!

**Comment by ppalaga** [comment]
#29 and #31 belong to this API design discussion.

**Comment by angelozerr** [comment]
@ppalaga I have fixed few bugs but now ec4e is working again. Thanks a lot for your great refactoring about clean API.

I would like to validate with you:

 * package names `org.eclipse.ec4j.core.model`, do you like it?
 * use `option` as name instead of using `property`, do you like it?

Otherwise, could you fix https://github.com/angelozerr/ec4j/issues/34 please by adding a sample with the API. Thanks!

**Comment by ppalaga** [comment]
`org.eclipse.ec4j.core.model` is a good package name for the classes it contains, with a small exception of the `EditorConfigHandler` that IMO belongs to the `parser` package. I have a PR underway that moves `EditorConfigHandler` to the `parser` package (plus a few other things).

As for `option` vs. `property`, I tend to prefer `property` because that's how they call it on http://editorconfig.org/. But I could live with `option` too. I any case, please do not refactor before I sent my next PR, or otherwise, I'll have a lot of work with rebasing.

> could you fix #34 please by adding a sample with the API.

Of course :)

**Comment by angelozerr** [comment]
> org.eclipse.ec4j.core.model is a good package name for the classes it contains, with a small exception of the EditorConfigHandler that IMO belongs to the parser package. I have a PR underway that moves EditorConfigHandler to the parser package (plus a few other things).

Cool!

> As for option vs. property, I tend to prefer property

Ok so we need to change that. As long as ec4j is not released we can do big refactoring. I have created an issue at https://github.com/angelozerr/ec4j/issues/41

> Of course :)

Thanks!

**Comment by angelozerr** [comment]
@ppalaga i think I can close this issue, no?

**Comment by ppalaga** [comment]
Please keep it open, I have one or two more things to propose.

**Comment by angelozerr** [comment]
@ppalaga can we close this issue now?

**Comment by ppalaga** [comment]
No, I still have a few things to propose.

**Comment by ppalaga** [comment]
https://github.com/ec4j/ec4j/pull/68 and https://github.com/ec4j/ec4j/issues/69 contain a few API changes/proposals that subsume here. Once those two are fixed/merged, the present issue can be closed.
