### ISSUE TITLE
Fix travis error with ctest

### ISSUE THREAD

**Issue by angelozerr** [ec4j/ec4j#38]
There are some errors with travis with ctest like https://travis-ci.org/angelozerr/ec4j/jobs/294055688#L2134

```
 85/182 Test  #85: braces_alpha_range1 .......................***Failed  Required regular expression not found.Regex=[^words=a[ 	
]*$
```

I'm not sure but perhaps the problem comes from with the name of my repository (angelozerr). It stats with a and it breaks the test. If it that how to fix that? @ppalaga have you time to investigate about this problem?

**Comment by ppalaga** [comment]
> perhaps the problem comes from with the name of my repository (angelozerr). It stats with a and it breaks the test.

That's hard to believe. It would be best to add some debug output to our code and write to a special log file so that it does not interfere with the cmake tests that use stdout and stderr.

**Comment by ppalaga** [comment]
This should become closeable after https://github.com/ec4j/ec4j/pull/68 gets merged.

**Comment by ppalaga** [comment]
We have 100% tests passed on TravisCI now.
