### ISSUE TITLE
Make a Session end at the end of its last property

### ISSUE THREAD

**Issue by angelozerr** [ec4j/ec4j#55]
@ppalaga I create this issue to define what is the end of Section.

Here a screenshot with your JUnit test:

![image](https://user-images.githubusercontent.com/1932211/32349275-bfab598a-c016-11e7-9b48-c50697592533.png)

The end section is used to define folding. So in your test it should be line 37.

But we can consider that too:

![image](https://user-images.githubusercontent.com/1932211/32350034-52ed7780-c019-11e7-929c-8ef84d7b557a.png)

In this case line is 32, but IMHO it's perhaps more hard to implement that.

I think I don't need enclosed location.

**Comment by ppalaga** [comment]
I am about to implement the second option: Make a Session end at the end of its last property. 

I am leaving the session start at the start of the `[` of the glob (unlike on your picture).
