### ISSUE TITLE
Pass the parent EditorConfig to Sections and the parent Section to Properties

### ISSUE THREAD

**Issue by angelozerr** [ec4j/ec4j#58]
@ppalaga I'm starting to develop Outline for Eclipse:

![image](https://user-images.githubusercontent.com/1932211/32431719-d1d5580c-c2d4-11e7-8e4c-f48b03dead33.png)

I need to know the parent of section and property https://github.com/angelozerr/ec4e/blob/master/org.eclipse.ec4e/src/main/java/org/eclipse/ec4e/internal/outline/EditorConfigContentProvider.java#L116

**Comment by ppalaga** [comment]
This is impossible with a truly immutable model. But I clearly see the need and I'll try to fin a way to trick it out.
