### ISSUE TITLE
Test locations of globs, properties, property names and values

### ISSUE THREAD

**Issue by angelozerr** [ec4j/ec4j#62]
Improve test https://github.com/angelozerr/ec4j/blob/master/core/src/test/java/org/eclipse/ec4j/core/parser/LocationAwareModelHandlerTest.java 

@ppalaga I think it should be better to have little test and use String instead of ClassPath for the .editorconfig content. I think it' smore readable to have that

**Comment by ppalaga** [comment]
> it should be better to have little test and use String instead of ClassPath for the .editorconfig content. I think it' smore readable to have that

In this specific case, I think the exact opposite: when writing tests for locations its super handy to be able to let my IDE to show me the real locations by opening a real file. I am really lazy to count lines and columns manually.

Except for that, I'll probably be more akin to use in-test strings for these purposes once Java starts having multiline strings like Groovy, Ceylon, Kotlin and many other languages.
