### ISSUE TITLE
Support location for comments

### ISSUE THREAD

**Issue by angelozerr** [ec4j/ec4j#63]
Today we can get commentsBlock but we cannot get span of comments block. I need this feature to implement folding for comments inside ec4e.

**Comment by ppalaga** [comment]
The individual `CommentLine` s have spans. It was easier to do it that way because we get the location info only per comment line from the parser. Isn't it sufficient for you to look at the firstLine's span.start and last line's span.end?

**Comment by angelozerr** [comment]
I would like to get start/end location for comments blocks. See 
https://github.com/angelozerr/ec4e/commit/48a4d5cb919aa29b75a5290e132a95e1391bd206#diff-da37f0dcf948cd11cca2c7a605ceff69R126
