### ISSUE TITLE
Support utf-8-bom encoding

### ISSUE THREAD

**Issue by ppalaga** [ec4j/ec4j#93]
See https://github.com/ec4j/editorconfig-maven-plugin/issues/35 reported by @kazuki-ma.

Observations: 

* We currently support only encodings supported by Java's `java.nio.charset.Charset.forName(String)` [1]. `utf-8-bom` is not there as you can see.
* EditorConfig docs states that `utf-8-bom` is one of the possible values of `charset` [2].

My standpoint:

I personally hold `utf-8-bom` for rare enough not to bother with finding a workaround for the lack of the native Java support. Clearly, such workaround is technically possible but I do not think I'll be wanting to fix this myself unless more people come and upvote this issue.

A contribution from the community is welcome, I am ready to give some general guidance where and how to fix this.

[1] https://docs.oracle.com/javase/8/docs/technotes/guides/intl/encoding.doc.html
[2] https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#charset

**Comment by ppalaga** [comment]
BTW, @dyadix does IntelliJ support opening UTF-8 files with BOM?

**Comment by kazuki-ma** [comment]
@ppalaga  Thank you for your handling.

We have multi-language (Kotlin / C++ / C#) and uses editorconfig-maven-plugin as top level formatter.
And, it may be not famous, C# and some other programming language requires `utf-8-bom` in case of source code contains CJK (Chinese-Japanese-Korean) literal or comment.

I think supporting `utf-8-bom` is ideal but @ppalaga's opinion is also reasonable.

I'm happy just ignored `charset = xxxx` in case of `xxxx` is not supported. How do you think?
